### ISSUE TITLE
Build Error : error: type of expression is ambiguous without more context when building iOS

### ISSUE THREAD

**Issue by RageshAntony** [infitio/flutter_socket_io#153] opened 2021-02-04 05:53 UTC
**Describe the bug**
when building I am getting following error 

                                        _
```
   adhara_socket_io-0.4.2+1/ios/Classes/AdharaSocket.swift:80:32: error: extraneous argument label 'with:' in call
                        socket.emit(eventName, with: data)
                                   ^           ~~~~~~

   project_name/adhara_socket_io-0.4.2+1/ios/Classes/AdharaSocket.swift:82:63: error: type of expression is ambiguous without more context
                        socket.emitWithAck(eventName, with: data).timingOut(after: 0) { data in
```

**Have you tried reproducing the issue with example available in this repo?**
No?

**To Reproduce**
Just build with new version of flutter

**Expected behavior**

**Device details:**

Flutter 1.22.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9b2d32b605 (12 days ago) • 2021-01-22 14:36:39 -0800
Engine • revision 2f0af37152
Tools • Dart 2.10.5

**Relevant Logs**
```
Add any relevant logs about the problem here.
```

**Comment by liqiang1995** [comment] 2021-02-16 17:59
I got the same error.
Did you fix?

**Comment by liqiang1995** [comment] 2021-02-16 18:00
![Uploading image.png…]()

**Comment by RageshAntony** [comment] 2021-02-16 18:02
No .

But The repo owner promised that they will fix it by next week

**Comment by liqiang1995** [comment] 2021-02-16 18:54
this package was working yesterday.
But after I have reinstalled the pod for a new package, I can not build iOS.
what is the problem?

**Comment by changyeun** [comment] 2021-02-23 13:00
i got the same error.
fix please

**Comment by tiholic** [comment] 2021-03-02 06:15
It is taking time for me to find the root cause of issue. Currently targeting to have the open PR related to redesign landed in next week.

**Comment by RageshAntony** [comment] 2021-03-02 06:17
Thanks. We expecting your fixes.

Thanks for starting to fix the issue

**Comment by 2peter3** [comment] 2021-03-03 23:03
a fix for this would be awesome

XCode: Version 12.4 (12D4e)
flutter: 1.22.6

**Comment by 2peter3** [comment] 2021-03-04 11:52
does anybody know a workaround to fix this?

**Comment by Shashoug** [comment] 2021-03-06 20:40
i have the same issue now, any updates?

**Comment by smasinde** [comment] 2021-03-16 09:20
support needed

**Comment by roskimlong** [comment] 2021-03-23 10:56
I met that error too

**Comment by Shashoug** [comment] 2021-03-23 11:59
@smasinde @roskimlong 
I have switched to another package and worked like charm. 
If you want guys i can provide you with the code and the steps. 
Happy coding.

**Comment by roskimlong** [comment] 2021-03-23 16:19
@Shashoug  I will switch too if there is nothing update about this issue for ios, but android is working well !!!

**Comment by Shashoug** [comment] 2021-03-23 16:21
@roskimlong 
I think you should switch. 
I switched because i had to move my app into production. 
I won't risk any issues because my app depends on Socket.IO

**Comment by roskimlong** [comment] 2021-03-23 16:24
@Shashoug okay, I also think about that too. Can you guys me some information or more samples of another Socket?

**Comment by Shashoug** [comment] 2021-03-23 16:25
@roskimlong 
Sure!
Just give me a couple of minutes to get things more clear.

**Comment by roskimlong** [comment] 2021-03-23 16:27
@Shashoug thanks beforehand brother!

**Comment by roskimlong** [comment] 2021-03-26 05:15
@tiholic any update brother we are waiting your new update ❤️

**Comment by tiholic** [comment] 2021-03-26 05:18
Looking at a few failing tests at the moment. Will share an update soon

**Comment by roskimlong** [comment] 2021-03-27 19:25
Yeah brother, I'm your big fan ❤️

**Comment by carman247** [comment] 2021-03-30 17:18
I'm getting the same error I think .. no idea what's going on 😢

**Comment by roskimlong** [comment] 2021-03-31 05:28
This problem is not yet fixed out!

**Comment by carman247** [comment] 2021-03-31 07:30
Just posting this here in case it helps ..

# Error

```    
    /Users/XXXX/XXXX/ios/Pods/Socket.IO-Client-Swift/Source/SocketIO/Engine/SocketEngine.swift:754:32: warning: immutable value 'reason' was never used; consider replacing with '_' or removing it
            case let .disconnected(reason, code):
                                   ^~~~~~
                                   _
    /Users/XXXX/XXXX/ios/Pods/Socket.IO-Client-Swift/Source/SocketIO/Engine/SocketEngine.swift:754:40: warning: immutable value 'code' was never used; consider replacing with '_' or removing it
            case let .disconnected(reason, code):
                                           ^~~~
                                           _
    /Users/XXXX/XXXX/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/adhara_socket_io-0.4.2+1/ios/Classes/AdharaSocket.swift:80:54: error: missing argument for parameter 'completion' in call
                        socket.emit(eventName, with: data)
                                                         ^
                                                         , completion: <#(() -> ())?#>
    /Users/XXXX/XXXX/ios/Pods/Socket.IO-Client-Swift/Source/SocketIO/Client/SocketIOClient.swift:226:15: note: 'emit(_:with:completion:)' declared here
        open func emit(_ event: String, with items: [SocketData], completion: (() -> ())?) {
                  ^
    /Users/XXXX/XXXX/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/adhara_socket_io-0.4.2+1/ios/Classes/AdharaSocket.swift:80:50: error: cannot convert value of type '[Any]' to expected argument type '[SocketData]'
                        socket.emit(eventName, with: data)
                                                     ^
    /Users/XXXX/XXXX/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/adhara_socket_io-0.4.2+1/ios/Classes/AdharaSocket.swift:80:50: note: arguments to generic parameter 'Element' ('Any' and 'SocketData') are expected to be equal
                        socket.emit(eventName, with: data)
                                                     ^
    /Users/XXXX/XXXX/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/adhara_socket_io-0.4.2+1/ios/Classes/AdharaSocket.swift:82:63: error: type of expression is ambiguous without more context
                        socket.emitWithAck(eventName, with: data).timingOut(after: 0) { data in
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

# Flutter doctor -v
```
[✓] Flutter (Channel stable, 2.0.3, on macOS 11.2.1 20D75 darwin-x64, locale en-GB)
    • Flutter version 2.0.3 at /Users/XXXX/XXXX/Developer/flutter
    • Framework revision 4d7946a68d (12 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/XXXX/XXXX/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • iPhone (mobile) • 1d1eb83ee2a8e15f8785d98f988973abd4e58f6a • ios            • iOS 14.4
    • Chrome (web)    • chrome                                   • web-javascript • Google Chrome 89.0.4389.90
```

# Podfile
```
# Uncomment this line to define a global platform for your project
platform :ios, '11.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
```

**Comment by carman247** [comment] 2021-03-31 12:45
I noticed that 2 pods had been updated from:

```
# Podfile.lock
- Socket.IO-Client-Swift (15.2.0)
   - Starscream (~> 3.1)
- Starscream (3.1.1)
```

to:
```
# Podfile.lock
- Socket.IO-Client-Swift (16.0.1)
   - Starscream (~> 4.0)
- Starscream (4.0.4)
```

reverting back to the previous versions allowed me to build on iOS

**Comment by IzGabs** [comment] 2021-03-31 20:17
@carman247  THANK YOU SO MUCH!!! This really helps, hope they fix this issue asap

@roskimlong Hey bud, did you see @carman247 answer already? It can work for you too

**Comment by roskimlong** [comment] 2021-04-01 17:34
@carman247  Thanks so much!! It's worked, but I need to downgrade Flutter version from 2.0
@IzGabs Thanks brother

**Comment by RageshAntony** [comment] 2021-04-01 17:40
I think this repo is inactive and deprecated

It's time to build a alternate one

**Comment by tiholic** [comment] 2021-04-06 10:38
@RageshAntony @roskimlong @IzGabs @carman247 @Shashoug @smasinde @liqiang1995 @changyeun @2peter3 

Released a new stable version (1.0.0) to pub.

Improvised maintenance of the project by adding integration tests along.

Please try and let know if this issue is resolved.

> _FYI: Socket v3/v4 support needs to be added yet_

**Comment by RageshAntony** [comment] 2021-04-06 10:41
Thanks very much

Please Let me check

Thanks for your dedication for fixing and starting maintenance again
🙏🙏🙏❤️

**Comment by roskimlong** [comment] 2021-04-07 15:15
I tried to add version 1.0.0 but the error still the same

.pub-cache/hosted/pub.dartlang.org/adhara_socket_io-1.0.0/ios/Classes/AdharaSocket.swift:69:53: note: arguments to generic parameter 'Element' ('Any' and 'SocketData') are expected to be equal
                    socket.emitWithAck(eventName, with: data).timingOut(after: 0) { data in

**Comment by tiholic** [comment] 2021-04-08 05:04
@roskimlong This log seems to be `note` only, while the actual error might be different.

For example, error log looks like this (notice the log level is printed as `:error:` in the log below - _I wantedly injected an error here for demonstration_. The log level you shared is `:note:` only)

![image](https://user-images.githubusercontent.com/14252381/113970880-532c8200-9855-11eb-97f5-acfea8571f5d.png)


Please share full logs if XCode build was failing.

Also share:
1. iOS version
2. XCode version
3. Simulator/device
4. Podfile

**Comment by roskimlong** [comment] 2021-04-08 11:29
The problem is still the same to the topic of issue 😌😌😌

**Comment by tiholic** [comment] 2021-04-08 17:24
@roskimlong 

This comment answers your issue https://github.com/infitio/flutter_socket_io/issues/153#issuecomment-811039639

You can see the new integration tests use the same dependencies and the last test was run on latest stable channel (2.0.3): https://github.com/infitio/flutter_socket_io/blob/master/test_integration/ios/Podfile.lock#L7

Otherwise, it would help if you can share your `Podfile.lock`

Here are few other steps you could try, if you haven't already:
1. `flutter clean`
2. delete `ios/Podfile.lock`
3. delete `ios/Pods`
4. rebuild the project

**Comment by roskimlong** [comment] 2021-04-08 17:27
Yes it's worked when I change in pod lock, version of socket and Starscream

**Comment by tiholic** [comment] 2021-04-10 17:37
Closing this issue as addressed. Feel free to re-open if required.

**Closed by tiholic** 2021-04-10 17:37 UTC
