### ISSUE TITLE
Hot Reload Causes Multiple SocketIO Client Instances

### ISSUE THREAD

**Issue by husmen73** [infitio/flutter_socket_io#124] opened 2020-04-25 12:31 UTC
**Describe the bug**
Server side gets lots of connection from device in debug mode when clieck the hot reload or restart button on Intellij IDEA IDE. The device can't see other connection processes except one connection. There isn't any other socket connection except one in release debug mode. Its only occurs in debug mode.

We are using deviceID for socket.id. So all generated socket.id's are same from same device connection. Therefore socket data replacing by undestroyed socket client instances. So we can't work efficiently in debug mode.

I see a clearInstance method but can't use with hot reload feature.

**Have you tried reproducing the issue with example available in this repo?**
Didn't tried.

**To Reproduce**
1. Run in debug mode on real device.
2. Check socketio server connection list. You will see one connection.
3. Change some code (unnessary code)
3. Click Hot Restart button
4. Check socketio server connection list. You will see multiple socket connection from same device.

**Expected behavior**
In debug mode, socket instance must be destroyed when click to hot reload mode.

**Device details:**
 - Device Type: Device
 - Model: Same all models
 - OS: Same all models
 - Package Version latest

**SocketIO Server Side Logs**
```
Port 4500 listening...
2020-04-25T20:00:01 - A User (0b96e4fab6a2f - ::ffff:192.168.1.83) connected.
2020-04-25T20:00:45 - A User (0b96e4fab6a2f - ::ffff:192.168.1.83) connected.
2020-04-25T20:00:45 - A User (0b96e4fab6a2f - ::ffff:192.168.1.83) connected.

```

**Comment by vksBhardwaj** [comment] 2020-05-07 11:07
@husmen73 our problems are different. Your problem is due to not maintain Activity lifecycle during Hot Restart.
But my problem is due to some header missing from backend

**Comment by tiholic** [comment] 2021-04-06 11:52
Duplicate of #6 

@husmen73 this is resolve in a new release v1.0.0

**Closed by tiholic** 2021-04-06 11:52 UTC

**Comment by ariefwijaya** [comment] 2021-04-13 01:30
Thanks bro @tiholic, finally you come back. I will stay with this plugin, best and easy to use
