### ISSUE TITLE
error when trying to launch on iOS

### ISSUE THREAD

**Issue by MorochoRochaDarwin** [infitio/flutter_socket_io#25] opened 2019-06-02 23:21 UTC
these are my dependences
```\
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  google_maps_flutter: ^0.5.15
  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  json_annotation: ^2.0.0
  flutter_spinkit: "^3.1.0"
  firebase_core: ^0.4.0
  firebase_auth: ^0.11.0
  google_sign_in: ^4.0.1+3
  pointycastle: ^1.0.1
  flutter_svg: ^0.12.0
  flutter_secure_storage: ^3.2.1+1
  adhara_socket_io: 0.1.9
```

and this is the output log 
```
    === BUILD TARGET firebase_auth OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/macboookpro/Documents/flutter/boton_pas/ios/Pods/Socket.IO-Client-Swift/Source/SocketIO/Engine/SocketEngine.swift:316:11: error: value of type 'WebSocket' has no member 'onHttpResponseHeaders'
            ws?.onHttpResponseHeaders = {[weak self] headers in
            ~~^ ~~~~~~~~~~~~~~~~~~~~~
```

**Comment by tiholic** [comment] 2019-06-05 05:47
@MorochoRochaDarwin Can you try pointing your dependency to this repo's master, and share your result here!

**Comment by tiholic** [comment] 2019-06-05 14:58
Fixed released in [0.1.11](https://pub.dev/packages/adhara_socket_io/versions/0.1.11)

**Comment by MorochoRochaDarwin** [comment] 2019-06-10 01:24
> Fixed released in [0.1.11](https://pub.dev/packages/adhara_socket_io/versions/0.1.11)

now we have the next errorr

```
1 warning generated.
    === BUILD TARGET adhara_socket_io OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/macboookpro/development/flutter/.pub-cache/hosted/pub.dartlang.org/adhara_socket_io-0.1.11/ios/Classes/AdharaSocketIoPlugin.m:2:9: fatal error: 'adhara_socket_io/adhara_socket_io-Swift.h' file not found
    #import <adhara_socket_io/adhara_socket_io-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by 1593929040** [comment] 2019-06-11 00:52
#import <adhara_socket_io/adhara_socket_io-Swift.h> 报错解决了么

**Comment by tiholic** [comment] 2019-08-11 08:35
@MorochoRochaDarwin can you try with latest release and check if this is resolved?

**Comment by tiholic** [comment] 2019-08-25 20:23
> now we have the next errorr

> 1 warning generated.
>     === BUILD TARGET adhara_socket_io OF PROJECT Pods WITH CONFIGURATION Debug ===
>     /Users/macboookpro/development/flutter/.pub-
>   .....
>             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

@MorochoRochaDarwin  @1593929040 
The issue is with opening the xcodeproj instead of xcworkspace. Try the below.


```bash
cd adhara_socket_io/example/ios
open Runner.xcworkspace/
```

**Closed by tiholic** 2019-08-25 20:23 UTC
